version: '3.8'

services:
  oracle-xe:
    image: gvenzl/oracle-xe
    container_name: oracle-xe-composed
    platform: linux/amd64
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: MyStrongPassword123
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/MyStrongPassword123@oracle-xe-composed:1521/XEPDB1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

  db-init:
    image: gvenzl/oracle-xe
    container_name: insuranceapi-db-init-1
    platform: linux/amd64
    depends_on:
      oracle-xe:
        condition: service_healthy
    volumes:
      - ./src/main/resources/db:/dbscripts
    entrypoint: ["/bin/bash", "/dbscripts/init_db.sh"]

  insurance-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insurance-api
    platform: linux/amd64
    depends_on:
      db-init:
        condition: service_completed_successfully
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-xe-composed:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: insurance_admin
      SPRING_DATASOURCE_PASSWORD: StrongPassword123
    ports:
      - "8080:8080"

volumes:
  oracle_data:
