-- create dedicated user/schema
CREATE USER insurance_admin IDENTIFIED BY StrongPassword123;
GRANT CONNECT, RESOURCE TO insurance_admin;
ALTER USER insurance_admin DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

-- connected as insurance_admin user create tables and constraints:

-- 1. INSURANCE_PRODUCTS
CREATE TABLE insurance_admin.INSURANCE_PRODUCTS (
    product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    base_premium NUMBER(10,2) NOT NULL,
    risk_factor_logic VARCHAR2(50) NOT NULL
);
ALTER TABLE insurance_admin.INSURANCE_PRODUCTS
ADD CONSTRAINT chk_risk_logic
CHECK (risk_factor_logic IN ('AGE_BASED', 'FLAT_RATE'));

-- 2. CUSTOMERS
CREATE TABLE insurance_admin.CUSTOMERS (
    customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) NOT NULL,
    CONSTRAINT uq_customers_email UNIQUE (email)
);
ALTER TABLE insurance_admin.CUSTOMERS
ADD (
    customer_name VARCHAR2(100) NOT NULL,
    date_of_birth DATE NOT NULL
);

-- 3. POLICIES
CREATE TABLE insurance_admin.POLICIES (
    policy_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    policy_number VARCHAR2(30) NOT NULL UNIQUE,
    product_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    coverage_amount NUMBER(15,2) NOT NULL,
    annual_premium NUMBER(15,2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    creation_date DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT fk_product
        FOREIGN KEY (product_id)
        REFERENCES insurance_admin.INSURANCE_PRODUCTS(product_id),
        
    CONSTRAINT fk_customer
        FOREIGN KEY (customer_id)
        REFERENCES insurance_admin.CUSTOMERS(customer_id)
);
CREATE SEQUENCE insurance_admin.policy_seq
START WITH 1000
INCREMENT BY 1
NOCACHE;

-- select from tables:
SELECT * FROM insurance_admin.INSURANCE_PRODUCTS;
SELECT * FROM insurance_admin.CUSTOMERS;
SELECT * FROM insurance_admin.POLICIES;